### ISSUE TITLE
Recipe Details

### ISSUE THREAD

**Issue by Flooooooooooorian** [neuefische/hh-java-23-1-teamproject-recipes#3]
"As a User I want to display all details of a Recipe on an extra page for each recipe.

- Create a GET-Endpoint "/api/recipes/{id}"
- In the frontend I want to see a single recipes on a details page
    - Details Component
    - Route to the Details Component
- write unit- and integrationtests

**Comment by bolabolor** [comment]
Datenbank müssen wir noch mit anschließen
